title: Applied Data Science @ Columbia
tagline: https://github.com/TZstatsADS
description: "Class Blog for Stat W4249"

url: http://TZstatsADS.github.io/
port: 3000
highlighter: rouge

permalink: /:year/:month/:day/:title.html


google_analytics: #

owner:
  name: Tian Zheng
  github: _tz33cu
  twitter: _tz33cu